### ISSUE TITLE
Can we use our own video feature for training?

### ISSUE THREAD

**Issue by FusionFont** [fletcherjiang/LLMEPET#1]
Firstly, thank you for your wonderful work! Using LLM as an encoder is such a peculiar idea.

The second one is that I tried to use the method provided in your paper, but I chose more layers, the 6-32 I used here, and got better results!

![image](https://github.com/user-attachments/assets/231aaa08-add7-40c4-8837-bc83b8d2c142)

The result is amazing so I want to use this method on my own task, so I would like to ask how I should go about extracting the features, can you explain it in detail?

Looking forward to your reply!

**Comment by fletcherjiang** [comment]
I am very glad that you got such a good result, as per your request I have attached the feature extraction code to you, also please note that you need to prepare your own json file in the same format.

```json
{"qid": , "query": "", "duration": , "vid": "", "":[[]]}
```
[feature_extraction.zip](https://github.com/user-attachments/files/16407083/feature_extraction.zip)
I hope your task goes well!

**Comment by CrazyGeG** [comment]
Hi, may I know how do you modify the number of layers (" but I chose more layers, the 6-32 I used here") in the code? Thank you for your help!!!!

**Comment by fletcherjiang** [comment]
> Hi, may I know how do you modify the number of layers (" but I chose more layers, the 6-32 I used here") in the code? Thank you for your help!!!!


@CrazyGeG  Hello, based on your question, you can find `first_layer` and `n_layers` in `llm_epet/scripts/train.sh`. You can modify them accordingly. For example, if you want to select layers 6-32, set `first_layer = 5` and `n_layers = 32`.

I hope my answer helps solve your issue.
