### ISSUE TITLE
Request for TVSum Checkpoint Release

### ISSUE THREAD

**Issue by upup-1** [fletcherjiang/LLMEPET#2]
Hi,

Thank you for your work! I am currently trying to run the code from this repository, but I noticed that the TVSum checkpoint mentioned in the README has not been released yet. Could you please let me know when it will be available?

Thank you!

**Comment by fletcherjiang** [comment]
Updated! Thanks for the heads up!
Btw, I'm still uploading because of limited space on my cloud drive.
