### ISSUE TITLE
corrupted qvlights.zip 

### ISSUE THREAD

**Issue by CrazyGeG** [fletcherjiang/LLMEPET#4]
Hi,

Thank you for the amazing work. I have tried to download the qvlights features and it seems corrupted. 
<img width="362" alt="Screenshot 2024-10-07 at 8 45 58 PM" src="https://github.com/user-attachments/assets/91afcfa8-5367-4e49-84e9-82e037041ce1">

**Comment by fletcherjiang** [comment]
I'm sorry you're getting this error, have you tried unzipping on a system other than MacOs? Linux for example.

If you're in a hurry, you can do it via https://github.com/showlab/UniVTG/blob/main/install.md
Download it, as my features are aligned with his as well.

Please do not hesitate to ask me if you have any questions.

**Comment by CrazyGeG** [comment]
Hi, I have downloaded features from UniVTG github, thank you for your helping!!!
